// Generated by genAreas.py

#ifndef areaSaveData_hpp
#define areaSaveData_hpp

struct AreaDataCastleF1Bedroom1{
    bool switchHit = false;
    bool doorClosed = true;
};
struct AreaDataCastleF1KeyRoom{
    bool chestOpen = false;
};
struct AreaDataCastleGFKeyRoom{
    bool chestOpen = false;
};
struct AreaDataCastleGFKitchen{
    bool switchHit = false;
    bool doorClosed = true;
};
struct AreaDataCastleGFThrone{
    bool leftDoorLocked = true;
    bool topDoorLocked = true;
};


struct AreaSaveData {
    AreaDataCastleF1Bedroom1 areaDataCastleF1Bedroom1;
    AreaDataCastleF1KeyRoom areaDataCastleF1KeyRoom;
    AreaDataCastleGFKeyRoom areaDataCastleGFKeyRoom;
    AreaDataCastleGFKitchen areaDataCastleGFKitchen;
    AreaDataCastleGFThrone areaDataCastleGFThrone;
};

#endif
